/**
 * Curated multi-word and single-token skills for deterministic matching.
 * Longer phrases are matched first (see skills.ts).
 */
export const SKILL_PHRASES: string[] = [
  "machine learning",
  "deep learning",
  "data engineering",
  "data science",
  "business intelligence",
  "power bi",
  "google cloud",
  "gcp",
  "azure devops",
  "aws lambda",
  "kubernetes",
  "terraform",
  "ansible",
  "jenkins",
  "github actions",
  "gitlab ci",
  "ci/cd",
  "cicd",
  "rest api",
  "graphql",
  "microservices",
  "event driven",
  "kafka",
  "rabbitmq",
  "redis",
  "postgresql",
  "sql server",
  "mysql",
  "mongodb",
  "dynamodb",
  "elasticsearch",
  "apache spark",
  "apache airflow",
  "dbt",
  "snowflake",
  "bigquery",
  "react",
  "react native",
  "next.js",
  "nextjs",
  "node.js",
  "nodejs",
  "express.js",
  "vue.js",
  "angular",
  "typescript",
  "javascript",
  "tailwind css",
  "material ui",
  "spring boot",
  "spring framework",
  ".net core",
  "asp.net",
  "entity framework",
  "django",
  "flask",
  "fastapi",
  "pytorch",
  "tensorflow",
  "scikit-learn",
  "pandas",
  "numpy",
  "tableau",
  "looker",
  "salesforce",
  "servicenow",
  "jira",
  "confluence",
  "figma",
  "ux research",
  "ui design",
  "product management",
  "project management",
  "agile",
  "scrum",
  "kanban",
  "risk management",
  "compliance",
  "penetration testing",
  "application security",
  "information security",
  "soc 2",
  "iso 27001",
  "blockchain",
  "solidity",
  "ethereum",
  "ios development",
  "android development",
  "swift",
  "kotlin",
  "objective-c",
  "ruby on rails",
  "php",
  "laravel",
  "go lang",
  "golang",
  "rust",
  "c++",
  "c#",
  "java",
  "python",
  "ruby",
  "scala",
  "elixir",
  "haskell",
  "bash",
  "powershell",
  "linux",
  "unix",
  "windows server",
  "active directory",
  "oauth",
  "openid connect",
  "saml",
  "jwt",
  "oauth2",
  "sso",
  "iam",
  "vpc",
  "cdn",
  "dns",
  "tcp/ip",
  "http",
  "https",
  "grpc",
  "websockets",
  "webrtc",
  "opencv",
  "nlp",
  "llm",
  "generative ai",
  "prompt engineering",
  "langchain",
  "vector database",
  "pinecone",
  "weaviate",
  "mlops",
  "devops",
  "site reliability",
  "sre",
  "observability",
  "prometheus",
  "grafana",
  "datadog",
  "splunk",
  "elk stack",
  "kibana",
  "logstash",
  "nginx",
  "apache http",
  "iis",
  "docker",
  "helm",
  "argocd",
  "istio",
  "linkerd",
  "cypress",
  "playwright",
  "selenium",
  "jest",
  "mocha",
  "pytest",
  "junit",
  "xunit",
  "nunit",
  "test automation",
  "performance testing",
  "load testing",
  "etl",
  "elt",
  "data modeling",
  "data warehousing",
  "dimensional modeling",
  "kimball",
  "informatica",
  "talend",
  "ssis",
  "ssrs",
  "ssas",
  "excel",
  "vba",
  "sharepoint",
  "power automate",
  "powerapps",
  "outsystems",
  "mendix",
  "salesforce apex",
  "apex",
  "lightning web components",
  "lwc",
  "sap",
  "oracle ebs",
  "peoplesoft",
  "workday",
  "netsuite",
  "stripe",
  "paypal",
  "pci-dss",
  "gdpr",
  "hipaa",
  "pharma",
  "clinical trials",
  "fda",
  "gxp",
  "sdlc",
  "stlc",
  "tdd",
  "bdd",
  "ddd",
  "clean architecture",
  "event sourcing",
  "cqrs",
  "nosql",
  "sql",
  "pl/sql",
  "t-sql",
  "oracle sql",
  "sqlite",
  "cassandra",
  "couchdb",
  "firebase",
  "supabase",
  "vercel",
  "netlify",
  "heroku",
  "digitalocean",
  "cloudflare",
  "fastly",
  "akamai",
  "webpack",
  "vite",
  "rollup",
  "esbuild",
  "babel",
  "eslint",
  "prettier",
  "sonarqube",
  "code review",
  "pair programming",
  "mentoring",
  "technical leadership",
  "people management",
  "stakeholder management",
  "cross-functional",
  "communication skills",
  "problem solving",
  "analytical skills",
];
